services:
  - type: web
    name: seorylie-production           # updated service name
    env: docker
    branch: main

    # Docker configuration
    dockerfilePath: ./Dockerfile.simple      # uses the simple Dockerfile without client build
    dockerContext: .
    dockerCommand: npm run start        # executes the production start script (final stage)

    plan: starter
    region: oregon

    # Health-check endpoint inside the container
    healthCheckPath: /health

    envVars:
      # Standard runtime flags
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

      # Critical secrets (synchronisation disabled)
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false

      # SEOWerks API integration
      - key: SEO_WORKS_API_KEY
        value: e7fcafb5d36ded4c9fb2fdc84b055357f15e00b4730c5c73597b64a7b90fc115

      # Non-secret, useful defaults (can be overridden in dashboard)
      - key: FRONTEND_URL
        value: https://seorylie.com
      - key: CORS_ORIGIN
        value: https://seorylie.com
