services:
  # Backend API Service
  - type: web
    name: cleanrylie-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: rylie-seo-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://rylie-seo-console.onrender.com
      - fromGroup: rylie-seo-secrets

  # Frontend Web Console
  - type: static
    name: rylie-seo-console
    repo: https://github.com/copp1723/seorylie
    branch: main
    rootDir: web-console
    buildCommand: cd web-console && npm install && npm run build
    staticPublishPath: web-console/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: rylie-seo-db
    databaseName: rylie_seo_production
    user: rylie_user
    region: oregon
    plan: starter

envVarGroups:
  - name: rylie-seo-secrets
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GA4_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GA4_PROJECT_ID
        sync: false
      - key: GA4_PRIVATE_KEY
        sync: false
      - key: GA4_KEY_ID
        sync: false
      - key: GA4_ENCRYPTION_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: REDIS_URL
        sync: false