services:
  - type: web
    name: seorylie-production           # updated service name
    env: node                          # Use Node.js environment instead of Docker
    branch: main
    
    # Build configuration
    buildCommand: NODE_ENV=development npm install && npm run build
    startCommand: npm start

    plan: starter
    region: oregon

    # Health-check endpoint inside the container
    healthCheckPath: /health

    envVars:
      # Standard runtime flags
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

      # Critical secrets (synchronisation disabled)
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false

      # SEOWerks API integration
      - key: SEO_WORKS_API_KEY
        sync: false

      # Non-secret, useful defaults (can be overridden in dashboard)
      - key: FRONTEND_URL
        value: https://seorylie.com
      - key: CORS_ORIGIN
        value: https://seorylie.com
