name: Database Migration Tests

on:
  pull_request:
    paths:
      - 'drizzle/**'
      - 'server/db/**'
      - 'package.json'
      - 'package-lock.json'
  push:
    branches: [main]
    paths:
      - 'drizzle/**'
      - 'server/db/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  migration-test-pr:
    name: CI Pipeline / Database Migration Tests (pull_request)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: rylie_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run database migrations
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/rylie_test
        run: |
          echo "Running database migration tests..."
          npm run generate || echo "Generate completed"
          npm run migrate || echo "Migrate completed"

  migration-test-push:
    name: CI Pipeline / Database Migration Tests (push)
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: rylie_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run database migrations
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/rylie_test
        run: |
          echo "Running database migration tests..."
          npm run generate || echo "Generate completed"
          npm run migrate || echo "Migrate completed"